export const SET_DRIVER_LOCATION = 'SET_DRIVER_LOCATION';
export const SET_RIDE_REQUESTS = 'SET_RIDE_REQUESTS';
export const SELECTED_RIDER = 'SELECTED_RIDER';
export const UPDATE_RIDE_REQUEST_STATUS = 'UPDATE_RIDE_REQUEST_STATUS';
export const SET_DRIVER_ADDRESS = 'SET_DRIVER_ADDRESS';
